### ISSUE TITLE
Reports "all packages keyworded already" inconsistently

### ISSUE THREAD

**Issue by matoro** [projg2/nattka#75]
I'm trying to request keywording for dev-util/tree-sitter-cli for all rust platforms.  However nattka refuses to generate a package list for multiple arches, and for some individual arches.

The following arches work:  `'~arm64 ~ppc64 ~riscv ~x86'` while these don't:  `~arm ~sparc`

```
$ nattka make-package-list dev-util/tree-sitter-cli
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/nattka", line 8, in <module>
    sys.exit(setuptools_main())
  File "/usr/lib/python3.10/site-packages/nattka/__main__.py", line 1063, in setuptools_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/python3.10/site-packages/nattka/__main__.py", line 1054, in main
    return getattr(cmd, args.command.replace('-', '_'))()
  File "/usr/lib/python3.10/site-packages/nattka/__main__.py", line 413, in make_package_list
    plist = dict(match_package_list(repo, b, only_new=True))
  File "/usr/lib/python3.10/site-packages/nattka/package.py", line 362, in match_package_list
    raise KeywordNoneLeft('package keywords in line with other '
nattka.package.KeywordNoneLeft: package keywords in line with other versions and none specified
```

```
$ nattka make-package-list -a '~arm ~arm64 ~ppc64 ~riscv ~sparc ~x86' dev-util/tree-sitter-cli
INFO:nattka:Iteration 1: running pkgcheck ...
gentoo -- updating profiles cache: x86  
INFO:nattka:New packages: virtual/rust
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/nattka", line 8, in <module>
    sys.exit(setuptools_main())
  File "/usr/lib/python3.10/site-packages/nattka/__main__.py", line 1063, in setuptools_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/python3.10/site-packages/nattka/__main__.py", line 1054, in main
    return getattr(cmd, args.command.replace('-', '_'))()
  File "/usr/lib/python3.10/site-packages/nattka/__main__.py", line 461, in make_package_list
    new_plist = dict(match_package_list(repo, b, only_new=True))
  File "/usr/lib/python3.10/site-packages/nattka/package.py", line 372, in match_package_list
    raise PackageListDoneAlready('all packages keyworded already')
nattka.package.PackageListDoneAlready: all packages keyworded already
```

```
$ nattka make-package-list -a '~arm' dev-util/tree-sitter-cli
INFO:nattka:Iteration 1: running pkgcheck ...
INFO:nattka:New packages: virtual/rust
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/nattka", line 8, in <module>
    sys.exit(setuptools_main())
  File "/usr/lib/python3.10/site-packages/nattka/__main__.py", line 1063, in setuptools_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/python3.10/site-packages/nattka/__main__.py", line 1054, in main
    return getattr(cmd, args.command.replace('-', '_'))()
  File "/usr/lib/python3.10/site-packages/nattka/__main__.py", line 461, in make_package_list
    new_plist = dict(match_package_list(repo, b, only_new=True))
  File "/usr/lib/python3.10/site-packages/nattka/package.py", line 372, in match_package_list
    raise PackageListDoneAlready('all packages keyworded already')
nattka.package.PackageListDoneAlready: all packages keyworded already
```

```
$ nattka make-package-list -a '~arm64' dev-util/tree-sitter-cli
INFO:nattka:Iteration 1: running pkgcheck ...
INFO:nattka:Time elapsed: 0:00:04.215723
INFO:nattka:Target CC: arm64@gentoo.org
INFO:nattka:Package list follows:
dev-util/tree-sitter-cli ~arm64
```

```
$ nattka make-package-list -a '~ppc64' dev-util/tree-sitter-cli
INFO:nattka:Iteration 1: running pkgcheck ...
INFO:nattka:Time elapsed: 0:00:04.214198
INFO:nattka:Target CC: ppc64@gentoo.org
INFO:nattka:Package list follows:
dev-util/tree-sitter-cli ~ppc64
```

```
$ nattka make-package-list -a '~arm64 ~ppc64 ~riscv ~x86' dev-util/tree-sitter-cli
INFO:nattka:Iteration 1: running pkgcheck ...
INFO:nattka:Time elapsed: 0:00:04.363949
INFO:nattka:Target CC: arm64@gentoo.org ppc64@gentoo.org riscv@gentoo.org x86@gentoo.org
INFO:nattka:Package list follows:
dev-util/tree-sitter-cli ~arm64 ~ppc64 ~riscv ~x86
```

Am I doing something incorrectly, or is the nattka behavior here wrong?

**Comment by mgorny** [comment]
Without checking, my guess is that it hits `package.mask` or version restriction somewhere. Unfortunately, it's pretty dumb, so it can't figure out what to do if pkgcheck tells it `foo/bar` is not satisfied but the newest version of `foo/bar` has the requested keyword.

**Comment by matoro** [comment]
After checking I believe this has something to do with the fact that those architectures have subprofiles which are wd40 (masked rust).  I was thinking rv32 was also (it should be) but it is not at the moment.

So how should this work?  It's not like we don't have rust packages that are keyworded for `~arm`, and I think this is going to block anybody from doing so in the future since nattka won't sanity-check it.

**Comment by mgorny** [comment]
This is only a best-effort option (as it says in the docs). You are welcome to try to improve the heuristics. In general, it should work as long as masks are in sync. I suppose it might be a problem if you're trying to keyword new packages that haven't been added to wd40 masks first — but really, what do you expect nattka to do, update the masks for you? ;-)

**Comment by matoro** [comment]
> This is only a best-effort option (as it says in the docs). You are welcome to try to improve the heuristics. In general, it should work as long as masks are in sync. I suppose it might be a problem if you're trying to keyword new packages that haven't been added to wd40 masks first — but really, what do you expect nattka to do, update the masks for you? ;-)

Ohhh I see that's what I was doing wrong!  Forgot to add the package itself to wd40 mask.  It still won't make the package list unless I specify the arches, but that should be good enough.
