### ISSUE TITLE
Breakage with pkgcore-0.12.18

### ISSUE THREAD

**Issue by mgorny** [projg2/nattka#78]
```pytb
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/nattka", line 8, in <module>
    sys.exit(setuptools_main())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nattka/__main__.py", line 1067, in setuptools_main
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nattka/__main__.py", line 1058, in main
    return getattr(cmd, args.command.replace('-', '_'))()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nattka/__main__.py", line 444, in make_package_list
    r = atom(d, eapi=eapi).no_usedeps
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snakeoil/caching.py", line 114, in __call__
    instance = super(WeakInstMeta, cls).__call__(*a, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/ebuild/atom.py", line 104, in __init__
    eapi_obj = eapi_mod.get_eapi(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/ebuild/eapi.py", line 486, in get_eapi
    if _valid_EAPI_regex.match(magic) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'EAPI'
```

**Comment by mgorny** [comment]
> <ferringb> That said, if you already have an eapi object, you probably want to do `eapi.atom_kls("<string-content>")`
